<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>Errors on Step by Step Dev</title><link>https://alexk2037.github.io/errors/</link><description>Recent content in Errors on Step by Step Dev</description><generator>Hugo -- gohugo.io</generator><lastBuildDate>Mon, 26 Jul 2021 00:27:40 -0400</lastBuildDate><atom:link href="https://alexk2037.github.io/errors/index.xml" rel="self" type="application/rss+xml"/><item><title>Prosody</title><link>https://alexk2037.github.io/errors/prosody/</link><pubDate>Mon, 26 Jul 2021 00:27:40 -0400</pubDate><guid>https://alexk2037.github.io/errors/prosody/</guid><description>Traceback[Bosh]: Attempt to perform arithmetic on a table value When I start a meeting I get the following output in the prosody logs:
Jul 26 04:17:12 mod_bosh info New BOSH session, assigned it sid &amp;#39;b0be5f11-8434-4b1d-b707-14a6a703df14&amp;#39; Jul 26 04:17:12 boshb0be5f11-8434-4b1d-b707-14a6a703df14 info Authenticated as df6d8268-d64a-4d0d-855f-e2c20b40c32f@freemeet.net Jul 26 04:17:12 mod_bosh error Traceback[bosh]: ...jitsi-meet/prosody-plugins/mod_external_services.lua:119: attempt to perform arithmetic on a table value stack traceback: ...jitsi-meet/prosody-plugins/mod_external_services.lua:119: in function &amp;#39;get_services&amp;#39; ...jitsi-meet/prosody-plugins/mod_external_services.lua:169: in function &amp;#39;?</description></item></channel></rss>